# Generated by Django 2.2 on 2021-06-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210614_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
