# Generated by Django 2.2 on 2021-05-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_sentence', models.CharField(max_length=200)),
                ('korean_sentence', models.CharField(max_length=200)),
                ('Memorization', models.CharField(max_length=50)),
            ],
        ),
    ]
