# Generated by Django 2.2 on 2021-06-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_note', '0003_sentence_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='Classification',
            new_name='classification',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='Memorization',
            new_name='memorization',
        ),
    ]
