# Generated by Django 2.2 on 2021-06-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_note', '0004_auto_20210605_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentence',
            old_name='classification',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='english_sentence',
            new_name='EN_word',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='korean_sentence',
            new_name='KO_word',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='memorization',
            new_name='memorize',
        ),
    ]
