# Generated by Django 2.2 on 2021-06-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_note', '0005_auto_20210606_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='EN_word',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
