# Generated by Django 2.2 on 2021-06-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_note', '0006_auto_20210630_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='EN_word',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='KO_word',
            field=models.TextField(blank=True, null=True),
        ),
    ]
