# Generated by Django 2.2 on 2021-05-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_note', '0002_auto_20210517_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='image',
        ),
    ]
