# Generated by Django 2.2 on 2021-05-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_note', '0004_auto_20210520_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='image',
        ),
    ]
