# Generated by Django 2.2 on 2021-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_note', '0005_auto_20210520_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='example',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.IntegerField(),
        ),
    ]
