# Generated by Django 2.2 on 2021-05-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_note', '0007_auto_20210522_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='big_unit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='middle_nuit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
