# Generated by Django 2.2 on 2021-05-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_note', '0008_auto_20210523_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='middle_nuit',
            new_name='middle_unit',
        ),
    ]
