# Generated by Django 2.2 on 2021-05-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_note', '0009_auto_20210523_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='unit',
        ),
    ]
