# Generated by Django 2.2 on 2021-06-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_note', '0010_remove_post_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dt_created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='post',
            name='dt_modified',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Modified'),
        ),
    ]
